import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const moduleURL=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const loadSource=(p,imports={},suffix='')=>{let s=stripTypeScriptTypes(read(p),{mode:'transform'});for(const [a,b] of Object.entries(imports))s=s.replaceAll(`'${a}'`,`'${b}'`);return moduleURL(s+suffix);};
const policyURL=loadSource('lib/commerce-policy.ts');const safetyURL=loadSource('lib/request-safety.ts');const schemaURL=loadSource('lib/commerce-schema.ts');
const runtimeURL=loadSource('lib/commerce-runtime.ts',{'./commerce-policy':policyURL,'./request-safety':safetyURL});
const dbURL=moduleURL('export function getD1Binding(){return globalThis.testD1;}');
const policy=await import(policyURL);const safety=await import(safetyURL);let seq=0;
const savedEnv={...process.env};const savedFetch=globalThis.fetch;
afterEach(()=>{globalThis.fetch=savedFetch;for(const k of Object.keys(process.env))if(!(k in savedEnv))delete process.env[k];Object.assign(process.env,savedEnv);});
function fixture(){
 const db=new DatabaseSync(':memory:');db.exec(`PRAGMA foreign_keys=ON;CREATE TABLE credit_ledger(user_id TEXT,amount INTEGER,source TEXT,expires_on TEXT,created_at INTEGER);CREATE TABLE decisions(id TEXT,user_id TEXT,result_json TEXT,verdict TEXT,status TEXT,updated_at INTEGER);`);
 globalThis.testD1={prepare(sql){let args=[];return {bind(...a){args=a;return this;},runSync(){const r=db.prepare(sql).run(...args);return {success:true,meta:{changes:Number(r.changes)}};},async run(){return this.runSync();},async first(){return db.prepare(sql).get(...args)??null;},async all(){return {results:db.prepare(sql).all(...args)};}};},async batch(items){db.exec('BEGIN IMMEDIATE');try{const out=items.map(i=>i.runSync());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};
 const url=loadSource('lib/commerce-store.ts',{'@/db':dbURL,'./commerce-schema':schemaURL,'./commerce-policy':policyURL,'./request-safety':safetyURL},`\n//fixture${++seq}`);
 return {db,url,store:()=>import(url)};
}
async function setup(credits=20){const f=fixture();const st=await f.store();await st.commerceDb();f.db.prepare("INSERT INTO credit_lots(id,user_id,kind,granted,available,source_key,created_at) VALUES('l1','u1','paid',?,?, 'p1',?)").run(credits,credits,Date.now());return {...f,st};}
const req=(over={})=>({userId:'u1',key:crypto.randomUUID(),hash:'hash',feature:'standard',credits:10,reserveMicro:100,dayCapMicro:1000,...over});
test('policy has one membership, three packs and no automatic rewards',()=>{assert.equal(policy.MEMBERSHIP.price,9900);assert.equal(policy.MEMBERSHIP.credits,140);assert.deepEqual(policy.CREDIT_PACKS.map(p=>[p.price,p.credits]),[[1900,20],[8900,100],[24900,300]]);assert.deepEqual(Object.values(policy.REWARDS),[0,0,0]);assert.equal(policy.FEATURES.standard.credits,10);});
test('AI and checkout fail closed without reviewed configuration',async()=>{const r=await import(runtimeURL);delete process.env.AI_SPEND_ENABLED;assert.equal(r.runtimeConfig().configured,false);assert.equal(r.checkoutReady(),false);assert.throws(()=>r.quote('standard'));});
test('unit contribution stays positive at full redemption and 24 KRW/C cost',()=>{for(const p of [...policy.CREDIT_PACKS,policy.MEMBERSHIP]){const net=p.price/1.1-p.price*.0374-p.price*.03-p.credits*24;assert.ok(net>0);assert.ok(net/(p.price/1.1)>.40);}});
test('cost meter rejects unknown models and malformed usage',()=>{assert.equal(policy.costMicroUSD('gpt-5.6-terra',8000,1200),30400);assert.throws(()=>policy.costMicroUSD('unknown',1,1));assert.throws(()=>policy.costMicroUSD('gpt-5.6-terra',-1,1));});
test('legacy data is preserved and a live balance is imported once without renewing expiry',async()=>{const f=fixture();f.db.prepare('INSERT INTO credit_ledger VALUES(?,?,?,?,?)').run('u1',8,'signup','2029-01-31',1);const st=await f.store();let w=await st.wallet('u1');assert.equal(w.available,8);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM credit_ledger').get().n,1);w=await st.wallet('u1');assert.equal(w.available,8);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM credit_lots').get().n,1);f.db.prepare('INSERT INTO credit_ledger VALUES(?,?,?,?,?)').run('u1',99,'signup','2029-02-01',Date.now()+1000000);assert.equal((await st.wallet('u1')).available,8);});
test('a successful run charges once; replay does not reserve twice',async()=>{const {st,db}=await setup();const input=req();const r=await st.reserveRun(input);assert.equal((await st.wallet('u1')).available,10);await st.recordUsage(r.run.id,'u1',{micro:60,input:20,output:10,providerId:'test'});await st.recordUsage(r.run.id,'u1',{micro:999,input:999,output:999,providerId:'other'});assert.equal(db.prepare('SELECT actual_micro FROM credit_runs').get().actual_micro,60);await st.completeRun(r.run.id,'u1',{verdict:'WAIT'},'decision-1');const replay=await st.reserveRun(input);assert.equal(replay.fresh,false);assert.equal(replay.run.decision_id,'decision-1');assert.equal((await st.wallet('u1')).available,10);await st.failRun(r.run.id,'u1');assert.equal((await st.wallet('u1')).available,10);});
test('failed and abandoned requests restore customer credits exactly once, not company budget',async()=>{const {st,db}=await setup();const r=await st.reserveRun(req());await st.failRun(r.run.id,'u1');await st.failRun(r.run.id,'u1');assert.equal((await st.wallet('u1')).available,20);assert.equal(db.prepare('SELECT committed_micro FROM credit_budget_days').get().committed_micro,100);const x=await st.reserveRun(req());db.prepare('UPDATE credit_runs SET created_at=? WHERE id=?').run(Date.now()-700000,x.run.id);assert.equal((await st.wallet('u1')).available,20);});
test('100 simultaneous requests cannot overspend or run parallel AI for one account',async()=>{const {st,db}=await setup();const out=await Promise.allSettled(Array.from({length:100},()=>st.reserveRun(req())));assert.equal(out.filter(o=>o.status==='fulfilled').length,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM credit_runs').get().n,1);assert.equal((await st.wallet('u1')).available,10);});
test('insufficient credits, expiry and frozen credits never start AI',async()=>{const {st,db}=await setup(9);await assert.rejects(()=>st.reserveRun(req()),e=>e.status===402);db.prepare('UPDATE credit_lots SET available=0').run();await assert.rejects(()=>st.reserveRun(req()),e=>e.status===402);assert.equal(db.prepare('SELECT COUNT(*) n FROM credit_runs').get().n,0);});
test('global budget rejects new work and rolls back customer reservations',async()=>{const {st,db}=await setup();await assert.rejects(()=>st.reserveRun(req({reserveMicro:1001,dayCapMicro:1000})),e=>e.status===429);assert.equal((await st.wallet('u1')).available,20);assert.equal(db.prepare('SELECT COUNT(*) n FROM credit_runs').get().n,0);});
test('actual cost over reserve trips a budget circuit instead of silently accumulating',async()=>{const {st,db}=await setup();const r=await st.reserveRun(req());await st.recordUsage(r.run.id,'u1',{micro:200,input:100,output:100,providerId:'test'});await st.completeRun(r.run.id,'u1',{verdict:'WAIT'});await assert.rejects(()=>st.reserveRun(req()),e=>e.status===429);assert.equal((await st.wallet('u1')).available,10);const b=db.prepare('SELECT * FROM credit_budget_days').get();assert.ok(b.committed_micro>b.cap_micro);});
test('database prevents cross-account allocations and partial charge completion',async()=>{const {st,db}=await setup();db.prepare('INSERT INTO credit_budget_days VALUES(?,?,?)').run('day',0,1000);db.prepare("INSERT INTO credit_runs(id,user_id,request_key,payload_hash,feature,credits,state,budget_day,reserved_micro,created_at,updated_at) VALUES('x','attacker','x','x','standard',10,'reserved','day',100,1,1)").run();assert.throws(()=>db.prepare("INSERT INTO credit_allocations VALUES('x','l1',10)").run(),/INVALID_ALLOCATION/);assert.throws(()=>db.prepare("UPDATE credit_runs SET state='completed',result_json='{}' WHERE id='x'").run(),/INCOMPLETE_ALLOCATION/);});
test('verified order grants once and full unused refund freezes then removes its credits',async()=>{const {st,db}=await setup();db.prepare("INSERT INTO billing_orders VALUES('o','u1','pack20','v7',1900,20,'pending',NULL,1,NULL)").run();assert.throws(()=>db.prepare("UPDATE billing_orders SET status='paid' WHERE id='o'").run(),/UNVERIFIED_PAYMENT/);db.prepare("UPDATE billing_orders SET status='paid',payment_key='p',paid_at=2 WHERE id='o'").run();db.prepare("UPDATE billing_orders SET status='paid' WHERE id='o'").run();assert.equal((await st.wallet('u1')).available,40);db.prepare("UPDATE billing_orders SET status='refund_pending' WHERE id='o'").run();assert.equal((await st.wallet('u1')).available,20);db.prepare("UPDATE billing_orders SET status='refunded' WHERE id='o'").run();assert.equal((await st.wallet('u1')).available,20);});
test('used credits cannot enter an automatic full refund',async()=>{const {db}=await setup();db.prepare("INSERT INTO billing_orders VALUES('o','u1','pack20','v7',1900,20,'pending',NULL,1,NULL)").run();db.prepare("UPDATE billing_orders SET status='paid',payment_key='p',paid_at=2 WHERE id='o'").run();db.prepare("UPDATE credit_lots SET available=19 WHERE source_key='order:o'").run();assert.throws(()=>db.prepare("UPDATE billing_orders SET status='refund_pending' WHERE id='o'").run(),/REFUND_REQUIRES_REVIEW/);});
test('untrusted origins, malformed JSON and oversized streaming bodies are rejected',async()=>{assert.throws(()=>safety.assertSameOrigin(new Request('https://buysor.test/x',{headers:{origin:'https://evil.test'}})));await assert.rejects(()=>safety.boundedJson(new Request('https://buysor.test',{method:'POST',headers:{'content-type':'application/json'},body:'not json'})));await assert.rejects(()=>safety.boundedJson(new Request('https://buysor.test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify('x'.repeat(50))}),10),e=>e.status===413);});
test('no random signup award, no legacy deletion and no public tier switch remain',()=>{const attendance=read('lib/attendance.ts');assert.doesNotMatch(attendance,/DELETE FROM (credit_ledger|attendance)/);assert.doesNotMatch(attendance,/VALUES\s*\(\?,\s*8\b/);assert.match(read('app/api/subscription/route.ts'),/405/);assert.doesNotMatch(read('lib/support-chat.ts'),/api\.openai\.com|api\.anthropic\.com/);});
test('home has useful sections without invented customer endorsements',()=>{const source=read('components/home-story.tsx');for(const id of ['how-it-works','decision-example','simple-pricing'])assert.ok(source.includes(id));assert.match(source,/FAQ/);assert.doesNotMatch(source,/5M users|100k 5-star|4\.9 rating/);});
