"use client";
import Link from 'next/link';
import {Camera,ArrowRight,Check,UserRound,Clock3,ShieldCheck,MessageCircle} from 'lucide-react';
import {usePreferences} from './preferences-provider';
import {CREDIT_PACKS,MEMBERSHIP,formatKRW} from '@/lib/commerce-policy';
import s from './home-story.module.css';
export function HomeStory(){
 const {language}=usePreferences();const ko=language==='ko';const t=(a:string,b:string)=>ko?a:b;
 const steps=[
 [t('보여주세요.','Show what you are considering.'),t('사진이나 스크린샷, 링크, 제품명으로 시작하세요. 모델명을 모르는 상태에서도 시작할 수 있습니다.','Start with a photo, screenshot, link or product name. You do not need every specification.')],
 [t('내 상황을 더해요.','Add your situation.'),t('예산과 용도, 지금 쓰는 제품까지. 선택형 질문에 답하고 더 하고 싶은 말은 자유롭게 적으세요.','Set a budget and explain your use and current products. Add anything the questions missed.')],
 [t('결론과 이유를 함께.','A decision, with reasons.'),t('지금 구매, 기다림, 구매하지 않기. 왜 그 결론인지와 무엇이 바뀌면 다시 봐야 하는지를 정리합니다.','Buy, wait or skip. Understand why, and which changes would call for another look.')]
 ];
 const faq=[
 [t('사진이 없어도 사용할 수 있나요?','Can I start without a photo?'),t('네. 제품명·링크·카테고리로도 시작합니다. 링크만으로 내용이 확인되지 않으면 가격이나 상세 정보를 추가로 입력해 주세요.','Yes. Use a product name, link or category. A link alone may not provide its contents; add price and details when needed.')],
 [t('반드시 월 구독을 해야 하나요?','Do I have to subscribe?'),t('아니요. 필요한 만큼 크레딧을 구매하는 방식을 기본으로 합니다. 자주 쓰는 분을 위한 월 멤버십은 별도 준비 중입니다.','No. Credit packs are the default. A separate monthly membership for frequent use is being prepared.')],
 [t('사진 인식과 구매판단을 따로 결제하나요?','Is a photo charged twice?'),t('표준 구매판단 10C에는 해당 건의 사진 입력이 포함됩니다. 사진로 시작했다고 1C를 추가로 차감하지 않습니다.','A standard 10C decision includes the photo for that request. There is no extra photo charge in that flow.')],
 [t('항상 최저가와 최신 정보를 알려주나요?','Is every price live and verified?'),t('아니요. 현재는 입력한 정보를 중심으로 판단하며, 실시간 최저가·재고·보증을 자동 검증했다고 표시하지 않습니다. 확인이 필요한 정보는 구분합니다.','No. The current workflow relies on supplied information. It does not claim to verify live lowest prices, availability or warranty. Missing facts stay marked as uncertain.')],
 [t('가입하면 크레딧을 주나요?','Are signup credits available?'),t('가입·출석·초대에 따른 자동 크레딧 보상은 없습니다. 직접 프로필을 작성하고 기존 결과를 다시 보는 것은 무료입니다.','There are no automatic signup, attendance or referral credits. Manual profiles and revisiting saved results are free.')]
 ];
 return <div className={s.story}>
 <section className={s.section} id="how-it-works"><header className={s.heading}><span>{t('사용 방법','HOW IT WORKS')}</span><h2>{t('고민은 짧게. 판단은 깊게.','Less searching. More deciding.')}</h2><p>{t('복잡한 스펙보다, 내게 필요한 것부터.','Start with what you need, not a specification sheet.')}</p></header>
 <div className={s.steps}>{steps.map(([a,b],i)=><article key={a}><b>0{i+1}</b><h3>{a}</h3><p>{b}</p></article>)}</div></section>
 <section className={`${s.section} ${s.example}`} id="decision-example"><div className={s.exampleCopy}><span>{t('결과 예시','A WORKED EXAMPLE')}</span><h2>{t('사지 않는 선택도,\n좋은 결론이니까.','Sometimes, keeping what you have\nis the better choice.')}</h2><p>{t('새 노트북을 살지 고민이라면. 지금 쓰는 제품으로 충분한지부터 함께 봅니다.','Considering a new laptop? First look at whether your current one still does the job.')}</p><small>{t('설명용 가상 사례입니다. 실제 고객의 분석이나 실시간 시세가 아닙니다.','Illustrative scenario, not a real customer result or live market analysis.')}</small></div>
 <article className={s.result}><div className={s.resultTop}><span>BUYSOR</span><b>WAIT · {t('기다리기','WAIT')}</b></div><h3>{t('지금은 교체보다,\n불편함부터 확인하세요.','Check the actual problem\nbefore replacing the laptop.')}</h3><dl><div><dt>{t('나의 상황','YOUR CONTEXT')}</dt><dd>{t('문서·강의 위주 / 현재 제품 작동 / 교체 예산 120만 원','Documents and classes / working laptop / budget set')}</dd></div><div><dt>{t('판단 근거','WHY')}</dt><dd>{t('현재 용도로는 성능 부족이 확인되지 않았습니다.','There is not enough evidence that performance is the limiting factor.')}</dd></div><div><dt>{t('다시 볼 조건','WHEN TO RECHECK')}</dt><dd>{t('실제 작업에 지장이 생기거나, 수리비가 확인될 때.','When real work is affected or you have a repair quote.')}</dd></div></dl><div className={s.alternatives}><span>{t('현재 제품 유지','Keep')}</span><span>{t('수리·보완','Repair')}</span><span>{t('신품·중고 교체','Replace')}</span></div></article></section>
 <section className={`${s.section} ${s.personal}`}><div className={s.personalMark}><UserRound size={60}/><span>{t('나를 알수록','YOUR CONTEXT MATTERS')}</span><strong>{t('같은 제품도,\n다른 결론.','Same product.\nDifferent decision.')}</strong></div><div><span className={s.kicker}>{t('나만의 구매 기준','YOUR DECISION PROFILE')}</span><h2>{t('매번 처음부터\n설명하지 않도록.','Your next decision\nstarts with your context.')}</h2><p>{t('예산, 용도, 보유 제품, 사용 환경과 앞으로의 계획. 직접 알려준 정보를 다음 판단에 함께 사용합니다.','Budget, use, products you own, environment and plans. The context you save is included in your next decision.')}</p><Link href="/profile">{t('바이저에게 나를 알려주기','Build my profile')} <ArrowRight size={16}/></Link></div></section>
 <section className={s.section} id="simple-pricing"><header className={s.heading}><span>{t('간단한 요금','SIMPLE PRICING')}</span><h2>{t('구독 없이, 필요한 만큼.','Only what you need. No subscription required.')}</h2><p>{t('첫 구매 고민 두 번, 1,900원부터. 서비스와 결제 검증을 마친 후 판매를 시작합니다.','Two standard decisions from KRW 1,900. Sales start after service and payment verification.')}</p></header><div className={s.packs}>{CREDIT_PACKS.map(p=><Link href="/credits" key={p.id}><span>{p.credits}C</span><strong>{formatKRW(p.price)}</strong><p>{t(`표준 판단 ${p.credits/10}회 상당`,`${p.credits/10} standard decisions`)}</p><b>{t('사용량과 상태 확인','See details')} <ArrowRight size={14}/></b></Link>)}</div><div className={s.membership}><span>{t('자주 쓰는 분을 위한 선택','An option for frequent use')}</span><strong>{t('월 멤버십','Monthly membership')} · {formatKRW(MEMBERSHIP.price)} / {MEMBERSHIP.credits}C</strong><Link href="/pricing">{t('준비 상태 보기','View preparation status')} <ArrowRight size={15}/></Link></div></section>
 <section className={`${s.section} ${s.trust}`}><header className={s.heading}><span>{t('결과보다 먼저, 신뢰','TRUST BEFORE A VERDICT')}</span><h2>{t('확실한 것과, 아직 모르는 것.','What is known. What still needs checking.')}</h2></header><div className={s.trustGrid}><article><ShieldCheck/><h3>{t('추측을 사실로 포장하지 않기','Keep uncertainty visible')}</h3><p>{t('근거가 없는 가격·발매일·보증 조건은 확인 필요로 남겁니다.','Prices, release dates and warranty terms need evidence, not confident guesses.')}</p></article><article><Clock3/><h3>{t('사용량은 시작 전에','See the cost before starting')}</h3><p>{t('필요한 크레딧을 먼저 보여줍니다. 정상 결과를 제공하지 못한 처리는 사용권을 복원합니다.','The required credits are shown first. A failed analysis releases the reserved credits.')}</p></article><article><MessageCircle/><h3>{t('설명할 수 있는 결론','A decision you can understand')}</h3><p>{t('결론만 보여주지 않고 이유·대안·주의점을 함께 정리합니다.','Read the reasons, alternatives and trade-offs alongside the recommendation.')}</p></article></div></section>
 <section className={`${s.section} ${s.faq}`}><header className={s.heading}><span>FAQ</span><h2>{t('시작 전, 궁금한 것들.','Before you start.')}</h2></header>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
 <section className={s.final}><span>BUYSOR</span><h2>{t('이거 살까?\n그 다음은 바이저.','Should I buy this?\nStart with BUYSOR.')}</h2><Link href="/lens"><Camera size={18}/>{t('내 구매 고민 확인하기','Start my decision')}<ArrowRight size={17}/></Link><p>{t('현재 공개 준비 버전입니다. 이용 가능 상태는 시작 화면에서 안내합니다.','Public preparation release. Availability is shown before you start.')}</p></section>
 <footer className={s.footer}><strong>BUYSOR</strong><nav><Link href="/usage-policy">{t('사용권 가이드','Usage guide')}</Link><Link href="/support">{t('고객지원','Support')}</Link><Link href="/credits">{t('크레딧','Credits')}</Link><Link href="/pricing">{t('멤버십','Membership')}</Link></nav></footer>
 </div>;
}
